// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9kzyXl4HI0p-PmI1Ev7WFAymZzn1uF7g',
    appId: '1:527389437123:android:44abfb3da476689ba34676',
    messagingSenderId: '527389437123',
    projectId: 'le-repere-1b000',
    storageBucket: 'le-repere-1b000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2rOCZiP2LsgJFsfHQ7ubd4s_XSzk9ZSg',
    appId: '1:527389437123:ios:813945c1e90e546fa34676',
    messagingSenderId: '527389437123',
    projectId: 'le-repere-1b000',
    storageBucket: 'le-repere-1b000.firebasestorage.app',
    androidClientId: '527389437123-2vn4t6rje3vrgqg9blb6jv6vepfv7jpa.apps.googleusercontent.com',
    iosClientId: '527389437123-70j9vqtv8cln1cv47jh706fev0v6obr6.apps.googleusercontent.com',
    iosBundleId: 'fr.insa.hdf.leRepere',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENY1jjoNs-7vGnoyeVoNyVb_PAMmv5IE',
    appId: '1:527389437123:web:f64d2715b9a5c36ea34676',
    messagingSenderId: '527389437123',
    projectId: 'le-repere-1b000',
    authDomain: 'le-repere-1b000.firebaseapp.com',
    storageBucket: 'le-repere-1b000.firebasestorage.app',
  );

}