-- Associations + Propositions de lieu (diagramme de classes).
-- Ajoute les deux classes manquantes du diagramme : Association et
-- PropositionLieu. Les autres classes existent deja :
--   Utilisateur / Administrateur -> table utilisateurs (+ enum user_role,
--   'admin' tenant lieu de la classe Administrateur)
--   Lieu  -> table lieux
--   Avis  -> table avis (relation "redige" Utilisateur->Avis,
--            "concerne" Avis->Lieu)
-- Note: versionnee en 170000 car la version 150000 etait deja prise sur le
-- distant par une autre migration.
-- Appliqué via: supabase db push

-- Association : donnees publiques d'une association du campus.
create table if not exists public.associations (
  id_association bigint generated by default as identity primary key,
  nom text not null,
  description text not null default '',
  contact text not null default ''
);

-- Statut du cycle de vie d'une proposition de lieu (idempotent).
do $$
begin
  if not exists (select 1 from pg_type where typname = 'proposition_statut') then
    create type public.proposition_statut as enum (
      'en_attente',
      'validee',
      'refusee'
    );
  end if;
end
$$;

-- PropositionLieu : un utilisateur "propose" un lieu, un admin le "valide".
create table if not exists public.propositions_lieu (
  id_proposition bigint generated by default as identity primary key,
  statut public.proposition_statut not null default 'en_attente',
  -- "concerne" : le lieu vise par la proposition. Nullable tant que le lieu
  -- definitif n'a pas encore ete cree en base.
  id_lieu text references public.lieux (id) on delete cascade,
  -- "propose" : l'auteur de la proposition.
  id_utilisateur uuid not null references auth.users (id) on delete cascade,
  -- "valide" : l'administrateur ayant traite la proposition.
  id_administrateur uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

-- RLS -----------------------------------------------------------------------
alter table public.associations enable row level security;
alter table public.propositions_lieu enable row level security;

-- Associations : lecture publique ; ecriture reservee admin / association.
drop policy if exists "associations_read_all" on public.associations;
create policy "associations_read_all" on public.associations
  for select using (true);
drop policy if exists "associations_write_staff" on public.associations;
create policy "associations_write_staff" on public.associations
  for all
  using (
    coalesce(auth.jwt() ->> 'user_role', 'utilisateur') in ('admin', 'association')
  )
  with check (
    coalesce(auth.jwt() ->> 'user_role', 'utilisateur') in ('admin', 'association')
  );

-- Propositions : l'auteur voit les siennes, le staff (admin/moderateur) voit tout.
drop policy if exists "propositions_select_own_or_staff" on public.propositions_lieu;
create policy "propositions_select_own_or_staff" on public.propositions_lieu
  for select using (
    auth.uid() = id_utilisateur
    or coalesce(auth.jwt() ->> 'user_role', 'utilisateur') in ('admin', 'moderateur')
  );
-- Tout utilisateur authentifie peut proposer un lieu (en son nom).
drop policy if exists "propositions_insert_own" on public.propositions_lieu;
create policy "propositions_insert_own" on public.propositions_lieu
  for insert with check (auth.uid() = id_utilisateur);
-- Validation / rejet : reserves au staff.
drop policy if exists "propositions_update_staff" on public.propositions_lieu;
create policy "propositions_update_staff" on public.propositions_lieu
  for update using (
    coalesce(auth.jwt() ->> 'user_role', 'utilisateur') in ('admin', 'moderateur')
  );
-- Suppression : l'auteur ou un admin.
drop policy if exists "propositions_delete_own_or_admin" on public.propositions_lieu;
create policy "propositions_delete_own_or_admin" on public.propositions_lieu
  for delete using (
    auth.uid() = id_utilisateur
    or coalesce(auth.jwt() ->> 'user_role', 'utilisateur') = 'admin'
  );

-- Grants (Data API) ---------------------------------------------------------
grant select on table public.associations to anon, authenticated;
grant insert, update, delete on table public.associations to authenticated;
grant usage, select on sequence public.associations_id_association_seq to authenticated;

grant select on table public.propositions_lieu to anon, authenticated;
grant insert, update, delete on table public.propositions_lieu to authenticated;
grant usage, select on sequence public.propositions_lieu_id_proposition_seq to authenticated;

-- Realtime (pour les .stream cote Flutter).
alter publication supabase_realtime add table public.associations, public.propositions_lieu;
