-- Schéma initial + RLS pour Le Repère (auth Supabase).
-- Appliqué via: supabase db push

-- Utilisateurs : profil applicatif lié au compte d'auth Supabase.
create table if not exists utilisateurs (
  id uuid primary key references auth.users (id) on delete cascade,
  nom text not null default '',
  email text not null default '',
  position_gps text not null default ''
);

-- Lieux : données publiques.
create table if not exists lieux (
  id text primary key,
  nom text not null,
  description text not null default '',
  latitude double precision not null default 0,
  longitude double precision not null default 0,
  horaire text not null default '',
  image_url text not null default '',
  categorie text not null default 'services'
);

-- Avis : appartiennent à un utilisateur authentifié.
create table if not exists avis (
  id_avis bigint generated by default as identity primary key,
  note int not null check (note between 1 and 5),
  commentaire text not null,
  created_at timestamptz not null default now(),
  id_lieu text not null references lieux (id) on delete cascade,
  id_utilisateur uuid not null references auth.users (id) on delete cascade
);

alter table utilisateurs enable row level security;
alter table lieux enable row level security;
alter table avis enable row level security;

-- Lieux : lecture pour tous (écriture réservée au service role / admin).
create policy "lieux_read_all" on lieux
  for select using (true);

-- Utilisateurs : chacun lit et gère sa propre ligne.
create policy "utilisateurs_self_select" on utilisateurs
  for select using (auth.uid() = id);
create policy "utilisateurs_self_insert" on utilisateurs
  for insert with check (auth.uid() = id);
create policy "utilisateurs_self_update" on utilisateurs
  for update using (auth.uid() = id);

-- Avis : lecture publique, écriture limitée à l'auteur.
create policy "avis_read_all" on avis
  for select using (true);
create policy "avis_insert_own" on avis
  for insert with check (auth.uid() = id_utilisateur);
create policy "avis_update_own" on avis
  for update using (auth.uid() = id_utilisateur);
create policy "avis_delete_own" on avis
  for delete using (auth.uid() = id_utilisateur);

-- Realtime (pour les .stream côté Flutter).
alter publication supabase_realtime add table lieux, avis, utilisateurs;
